### ISSUE TITLE
дает ошибку ну похуй ну просто говорю

### ISSUE THREAD

**Issue by axx1oma** [neverlosecc/api-documentation#31]
local localplayer = g_EntityList:GetClientEntity(g_EngineClient:GetLocalPlayer())
local weapon_handle = localplayer:GetWeapon()
local weapon = g_EntityList:GetClientEntityFromHandle(weapon_handle)
local isWeapon = weapon:IsWeapon()
print(isWeapon)

эта штука в апи

**Comment by elleqt** [comment]
`local localplayer = g_EntityList:GetClientEntity(g_EngineClient:GetLocalPlayer())
local weapon = g_EntityList:GetClientEntity(localplayer:GetWeapon():EntIndex())
local isWeapon = weapon:IsWeapon()
print(isWeapon)`
