### ISSUE TITLE
is dormant

### ISSUE THREAD

**Issue by axx1oma** [neverlosecc/api-documentation#42]
is it working? 
local entity = g_EntityList:GetClientEntity(g_EngineClient:GetLocalPlayer())
local player = entity:GetPlayer()
local is_dormant = player:IsDormant()
print(is_dormant)

everytime it gives me false

RU

Это работает? 
При любом случае дает мне 0.

**Comment by es3n1n** [comment]
why would you even check m_bDormant for localplayer

**Comment by axx1oma** [comment]
oh yes but why it is in api 
maybe it will be better??

local players = g_EntityList:GetPlayers()
local local_player = g_EntityList:GetLocalPlayer()

for _, ply in ipairs(players) do
    if not ply:IsTeamMate() and ply:IsDormant() then
    print("dormant")
    end
end

**Comment by es3n1n** [comment]
> oh yes but why it is in api

ref?

**Comment by axx1oma** [comment]
?

**Comment by es3n1n** [comment]
fixed(?) in d609add96b17b592ac6aa5104f3a0aa1d4ff155b
