### ISSUE TITLE
Probably Api Issue

### ISSUE THREAD

**Issue by 300cps** [neverlosecc/api-documentation#49]
**Code From Api** 
```
local GetNetChannelInfo = EngineClient.GetNetChannelInfo()
local server_ip = GetNetChannelInfo:GetAddress()
print(server_ip)
```

**Error**
```
Failed to load lua New Script --ERROR--
[string "local GetNetChannelInfo = En..."]:2: attempt to index local 'GetNetChannelInfo' (a nil value)
stack traceback:
	[string "local GetNetChannelInfo = En..."]:2: in main chunk--

```

![probablyissue](https://user-images.githubusercontent.com/95547024/144723366-c0420fa1-e844-4b56-a8da-b5e84adcc3ba.png)

**Comment by elleqt** [comment]
While you are not in game NetChannelInfo always nil.

**Comment by 300cps** [comment]
> While you are not in game NetChannelInfo always nil.

Its should not crash but can write message like not connected into server

**Comment by es3n1n** [comment]
> > While you are not in game NetChannelInfo always nil.
> 
> Its should not crash but can write message like not connected into server

it shouldn't

**Comment by 300cps** [comment]
Ok so thanks to all for replies ill close it
