### ISSUE TITLE
issue in api :0

### ISSUE THREAD

**Issue by axx1oma** [neverlosecc/api-documentation#51]
-- @summary: Prints the amount of bullets in clip and max bullets in clip available

local clip = weap:GetProp("DT_BaseCombatWeapon", "m_iClip1")
local max_clip = weap:GetmaxClip()

print("Bullets in clip: "..tostring(clip).."/"..tostring(max_clip)

Function GetmaxClip - is incorrect. 
error - 
[string "-- @summary: Prints the amou..."]:7: attempt to call method 'GetmaxClip' (a nil value)

Replace it with: GetMaxClip; working :)

**Comment by elleqt** [comment]
Просто опечатка, исправлено.
